In [ ]:
import torch
import numpy as np

In [ ]:
scalar= torch.tensor(2)
scalar

tensor(2)

In [ ]:
scalar.ndim, scalar.shape

(0, torch.Size([]))

In [ ]:
vector= torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim , vector.shape

(1, torch.Size([3]))

In [ ]:
MATRIX=torch.tensor([[1,2,3],
                    [3,4,5]])
MATRIX

tensor([[1, 2, 3],
        [3, 4, 5]])

In [ ]:
MATRIX.ndim, MATRIX.shape

(2, torch.Size([2, 3]))

In [ ]:
TENSOR=torch.tensor([[[1,2,3],
                      [3,4,5],
                      [3,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [3, 4, 5]]])

In [ ]:
TENSOR.ndim,TENSOR.shape

(3, torch.Size([1, 3, 3]))

In [ ]:
num_array=np.ones((1,2,3), dtype='int')

TENSOR_FROM_NUMPY=torch.tensor(num_array)

TENSOR_FROM_NUMPY

tensor([[[1, 1, 1],
         [1, 1, 1]]])

In [ ]:
tens_to_numpy=TENSOR_FROM_NUMPY.numpy()
tens_to_numpy

array([[[1, 1, 1],
        [1, 1, 1]]])

# Random Tensor

In [ ]:
torch.rand(size=(1,2,3))

# or torch.rand((1,2,3))

tensor([[[0.7805, 0.5581, 0.8158],
         [0.9666, 0.0665, 0.2786]]])

In [ ]:
torch.randint(low=0, high=10, size=(1, 2, 3)) #numer between 0-9 inclusive

#or torch.randint(0, 10, size=(1, 2, 3))

tensor([[[9, 5, 3],
         [9, 1, 6]]])

In [ ]:
torch.zeros((1,4,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
torch.ones((1,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [ ]:
one_to_ten=torch.arange(0,11) # get number between 0-9
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
even_num_upto_20=torch.arange(0,21,2) #start end step
even_num_upto_20

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
ten_zero=torch.zeros_like(even_num_upto_20)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
ten_zero=torch.ones_like(even_num_upto_20)
ten_zero

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Tensor Datatypes

For all dtypes: ` https://pytorch.org/docs/stable/tensors.html`

In [ ]:
# torch.float32 ----> by default tensor dype is float32

float_32=torch.tensor([1.,2.,3.],
                      dtype=torch.float32, # what data type the tensor is?
                      device=None, # what device to use for processing tensors?
                      requires_grad=False) # whether or not to track gradients with this tensors operations?
float_32.dtype

torch.float32

In [ ]:
#torch.float16
float_16=torch.tensor([1.,2.,3.],dtype=torch.float16, device=None, requires_grad=False)
float_16.dtype

torch.float16

In [ ]:
# torch.int32
int_32=torch.tensor([1.,2.,3.],dtype=torch.int32, device=None, requires_grad=False)
print(int_32)

tensor([1, 2, 3], dtype=torch.int32)


In [ ]:
# torch.int16
int_16=torch.tensor([1.,2.,3.],dtype=torch.int16, device=None, requires_grad=False)
print(int_16)

tensor([1, 2, 3], dtype=torch.int16)


In [ ]:
# torch.int8
int_8=torch.tensor([1.,2.,3.],dtype=torch.int8, device=None, requires_grad=False)
print(int_8)

tensor([1, 2, 3], dtype=torch.int8)


# conversion of tensors dtype

In [ ]:
f16=float_32.type(torch.float16)
print(f16)

tensor([1., 2., 3.], dtype=torch.float16)


In [ ]:
int16=float_32.type(torch.int16)
print(int16)

tensor([1, 2, 3], dtype=torch.int16)


# Tensors Operations

In [ ]:
A= torch.tensor([1,2,3])
B=torch.tensor([3,4,5])

In [ ]:
#Addition
A+B
# torch.add(A,B)

tensor([4, 6, 8])

In [ ]:
#Substraction
A-B

tensor([-2, -2, -2])

In [ ]:
#Element wise multiply
A*B
#torch.mul(A,B)

tensor([ 3,  8, 15])

In [ ]:
#Matrix Multiplication
A@B
#torch.matmul(A,B)
#torch.mm(A,B)

tensor(26)

In [ ]:
#.item() is used to extract number form tesor
torch.matmul(A,B).item()

26

# useful functions

In [ ]:
T=torch.arange(0,10)
T

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
T.max().item()

9

In [ ]:
T.min().item()

0

In [ ]:
T.sum().item()

45

In [ ]:
T=T.type(torch.float32) #the dtype must be float for calculating mean
T.mean().item()

4.5

In [ ]:
T.argmin().item() # returns index of lowest number

0

In [ ]:
T.argmax().item() # returns index of highest number

9

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshape/View -  reshapes an input tensor to a defined shape
* Stacking - combine multiple tensors on top of each other (vstack) or side by side
(hstack)
* Squeeze - removes all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor

## Reshape

In [ ]:
A= torch.arange(1,11)
A, A.size()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
A.reshape(5,2),A.reshape(2,5) # 5 rows 2 columns and 2 rows 5 columns
# rule- for reshape the original size of the tensor must be multiple of new formimg tensors like [10]= 2X5, 5X2

(tensor([[ 1,  2],
         [ 3,  4],
         [ 5,  6],
         [ 7,  8],
         [ 9, 10]]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]))

## View

In [ ]:
B=A.view(5,2)
B

tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]])

# Stack

In [ ]:
S= torch.arange(1,11,2)
Y=torch.arange(11,21,2)

print(S)
print("\n")
print(Y)

tensor([1, 3, 5, 7, 9])


tensor([11, 13, 15, 17, 19])


In [ ]:
# dim=0 stack below /rowwise
x_stacked=torch.stack([S,Y],dim=0)
x_stacked

tensor([[ 1,  3,  5,  7,  9],
        [11, 13, 15, 17, 19]])

In [ ]:
# dim=1 stack sidewise /columnwise
x_stacked=torch.stack([S,Y],dim=1)
x_stacked

tensor([[ 1, 11],
        [ 3, 13],
        [ 5, 15],
        [ 7, 17],
        [ 9, 19]])

# Squeeze

In [ ]:
M = torch.rand(1,2,5)
print(M,'\n')
print(M.shape)

tensor([[[0.0876, 0.9174, 0.5076, 0.9379, 0.2919],
         [0.2684, 0.9028, 0.5993, 0.7906, 0.2452]]]) 

torch.Size([1, 2, 5])


In [ ]:
Z=M.squeeze() #removes 1 dim
print(Z,'\n')
print(Z.shape)

#we cant further squeeze since shape has not got 1 here torch.Size([2, 5])

tensor([[0.0876, 0.9174, 0.5076, 0.9379, 0.2919],
        [0.2684, 0.9028, 0.5993, 0.7906, 0.2452]]) 

torch.Size([2, 5])


# Unsqueeze

In [ ]:
N = torch.rand(2,5)
print(N,'\n')
print(N.shape)

tensor([[0.7673, 0.3048, 0.4905, 0.3399, 0.2974],
        [0.4137, 0.7717, 0.4588, 0.2951, 0.5826]]) 

torch.Size([2, 5])


In [ ]:
# here dim=0 is outer dim=1 is inner
print(N.unsqueeze(dim=0),N.unsqueeze(dim=0).shape,"\n")
print(N.unsqueeze(dim=1),N.unsqueeze(dim=1).shape,"\n")

tensor([[[0.7673, 0.3048, 0.4905, 0.3399, 0.2974],
         [0.4137, 0.7717, 0.4588, 0.2951, 0.5826]]]) torch.Size([1, 2, 5]) 

tensor([[[0.7673, 0.3048, 0.4905, 0.3399, 0.2974]],

        [[0.4137, 0.7717, 0.4588, 0.2951, 0.5826]]]) torch.Size([2, 1, 5]) 



# Check for GPU Access With Pytorch

In [ ]:
import torch
"Cuda Available" if torch.cuda.is_available() else "CPU"

'CPU'

# Running Tenors on GPU

In [ ]:
A= torch.tensor([1,2,3])
device=A.device
print('The Tensor will be Processed on :',A.device)

The Tensor will be Processed on : cpu


In [ ]:
A = A.to(device) #we can make our tensor to run on device 1)cpu or 2)Gpu
A

tensor([1, 2, 3])